# Generated by Django 4.2.23 on 2025-06-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='feedback',
        ),
    ]
